name: SwiftPan
options:
  bundleIdPrefix: com.liaojinxuan666
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

targets:
  SwiftPan:
    type: application
    platform: iOS
    sources:
      - App
      - Core
      - Features
      - Models
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.liaojinxuan666.SwiftPan
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        SWIFT_VERSION: "5.0"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""